### ISSUE TITLE
[Bug]: navbar 需要更新对应的 exampleSite 的配置文件

### ISSUE THREAD

**Issue by Sciroccogti** [cmpute/hugo-theme-stacked#3]
### What happened?

4acdc4268ceeaff43e47f10cf94bf666cc3c1aaa 引入的 navbar 需要更新对应的 exampleSite 的配置文件：
```yaml
params:
    widgets:
        page:
            - type: navbar
```

### Hugo version

0.110.0

### Theme version

5d5c810

### Link to the page with bug

https://demo.stack.jimmycai.com
